#!/usr/bin/env python3
"""Write the service worker for a built web app (docs/plan.md, S3).

    python tools/web-sw.py app/build/web

Lists every file the build produced except the content database (the app
keeps that in the browser's own storage once loaded; caching a 170 MB
asset twice helps nobody) and except anything under screenshots/ (the
contact sheet lives on the site but is not the app: nobody downloads it
without opening that page) and writes build/web/sw.js: on install it
caches all of them, on activate it drops caches of earlier builds, and
it answers same-origin requests from the cache first, falling back to
the network, and a navigation with no network from the cached index. The
cache name carries a hash of the files, so a new build is a new cache.
Runs after `flutter build web`; nothing in git lists a file that the
build might not produce.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

SKIP_SUFFIXES = (".sqlite", ".part")
SKIP_NAMES = {"sw.js", "flutter_service_worker.js", ".last_build_id"}
# Top-level directories that are on the site but are not the app.
SKIP_DIRS = {"screenshots"}

TEMPLATE = """// Seven Readings service worker. Generated by tools/web-sw.py at build
// time; do not edit. Cache %(cache)s, %(count)d files.
const CACHE = %(cache_json)s;
const PRECACHE = %(files_json)s;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // The content database is the app's business (browser storage), never ours;
  // the screenshots page is not the app.
  if (url.pathname.endsWith('.sqlite') || url.pathname.startsWith('/screenshots/')) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => (request.mode === 'navigate' ? caches.match('index.html') : undefined));
    }),
  );
});
"""


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(__doc__)
        return 2
    root = Path(argv[0]).resolve()
    if not (root / "index.html").exists():
        print(f"{root}: no index.html; build the web app first")
        return 1
    files: list[str] = []
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        if path.name in SKIP_NAMES or path.suffix in SKIP_SUFFIXES:
            continue
        if rel.split("/", 1)[0] in SKIP_DIRS:
            continue
        files.append(rel)
        digest.update(rel.encode())
        digest.update(path.read_bytes())
    cache = "sevenreadings-" + digest.hexdigest()[:16]
    precache = ["./", *files]
    text = TEMPLATE % {
        "cache": cache,
        "count": len(precache),
        "cache_json": json.dumps(cache),
        "files_json": json.dumps(precache, indent=2),
    }
    (root / "sw.js").write_text(text, encoding="utf-8")
    total = sum((root / f).stat().st_size for f in files)
    print(f"sw.js: {cache}, {len(precache)} entries, {total / 1e6:.1f} MB precached")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
